@echo off
Title Spotify
color 3
taskkill /f /im spotify.exe  
del /f/s/q "%appdata%\Spotify\SpotifyMigrator.exe" 
del /f/s/q "%appdata%\Spotify\SpotifyStartupTask.exe" 
del /f/s/q "%appdata%\Spotify\Apps\Buddy-list.spa" 
del /f/s/q "%appdata%\Spotify\Apps\Concert.spa" 
del /f/s/q "%appdata%\Spotify\Apps\Concerts.spa" 
del /f/s/q "%appdata%\Spotify\Apps\radio-hub.spa" 
del /f/s/q "%appdata%\Spotify\Apps\station.spa" 
del /f/s/q "%appdata%\Spotify\Apps\stations.spa" 
del /f/s/q "%appdata%\Spotify\Apps\Error.spa" 
del /f/s/q "%appdata%\Spotify\Apps\Findfriends.spa" 
del /f/s/q "%appdata%\Spotify\Apps\Show.spa" 
del /f/s/q "%appdata%\Spotify\Apps\Buddy-list.spa" 
red delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "Spotify" /f 

del /f/s/q "%appdata%\Spotify\locales\am.pak" 
del /f/s/q "%appdata%\Spotify\locales\ar.mo" 
del /f/s/q "%appdata%\Spotify\locales\ar.pak" 
del /f/s/q "%appdata%\Spotify\locales\bg.pak" 
del /f/s/q "%appdata%\Spotify\locales\bn.pak" 
del /f/s/q "%appdata%\Spotify\locales\ca.pak" 
del /f/s/q "%appdata%\Spotify\locales\cs.mo" 
del /f/s/q "%appdata%\Spotify\locales\cs.pak" 
del /f/s/q "%appdata%\Spotify\locales\da.pak" 
del /f/s/q "%appdata%\Spotify\locales\de.mo" 
del /f/s/q "%appdata%\Spotify\locales\de.pak" 
del /f/s/q "%appdata%\Spotify\locales\el.mo" 
del /f/s/q "%appdata%\Spotify\locales\el.pak" 
del /f/s/q "%appdata%\Spotify\locales\en-GB.pak" 
del /f/s/q "%appdata%\Spotify\locales\et.pak" 
del /f/s/q "%appdata%\Spotify\locales\fa.pak" 
del /f/s/q "%appdata%\Spotify\locales\fi.mo" 
del /f/s/q "%appdata%\Spotify\locales\fi.pak" 
del /f/s/q "%appdata%\Spotify\locales\fil.pak" 
del /f/s/q "%appdata%\Spotify\locales\fr.mo" 
del /f/s/q "%appdata%\Spotify\locales\fr.pak" 
del /f/s/q "%appdata%\Spotify\locales\fr-CA.mo" 
del /f/s/q "%appdata%\Spotify\locales\gu.pak" 
del /f/s/q "%appdata%\Spotify\locales\he.mo" 
del /f/s/q "%appdata%\Spotify\locales\he.pak" 
del /f/s/q "%appdata%\Spotify\locales\hi.pak" 
del /f/s/q "%appdata%\Spotify\locales\hr.pak" 
del /f/s/q "%appdata%\Spotify\locales\hu.mo" 
del /f/s/q "%appdata%\Spotify\locales\hu.pak" 
del /f/s/q "%appdata%\Spotify\locales\id.mo" 
del /f/s/q "%appdata%\Spotify\locales\id.pak" 
del /f/s/q "%appdata%\Spotify\locales\it.mo" 
del /f/s/q "%appdata%\Spotify\locales\it.pak" 
del /f/s/q "%appdata%\Spotify\locales\ja.mo" 
del /f/s/q "%appdata%\Spotify\locales\ja.pak" 
del /f/s/q "%appdata%\Spotify\locales\kn.pak" 
del /f/s/q "%appdata%\Spotify\locales\ko.mo" 
del /f/s/q "%appdata%\Spotify\locales\ko.pak" 
del /f/s/q "%appdata%\Spotify\locales\lt.pak" 
del /f/s/q "%appdata%\Spotify\locales\lv.pak" 
del /f/s/q "%appdata%\Spotify\locales\ml.pak" 
del /f/s/q "%appdata%\Spotify\locales\mr.pak" 
del /f/s/q "%appdata%\Spotify\locales\ms.mo" 
del /f/s/q "%appdata%\Spotify\locales\ms.pak" 
del /f/s/q "%appdata%\Spotify\locales\nb.pak" 
del /f/s/q "%appdata%\Spotify\locales\nl.mo" 
del /f/s/q "%appdata%\Spotify\locales\nl.pak" 
del /f/s/q "%appdata%\Spotify\locales\pl.mo" 
del /f/s/q "%appdata%\Spotify\locales\pl.pak" 
del /f/s/q "%appdata%\Spotify\locales\pt-PT.pak" 
del /f/s/q "%appdata%\Spotify\locales\pt-BR.pak" 
del /f/s/q "%appdata%\Spotify\locales\pt-BR.mo" 
del /f/s/q "%appdata%\Spotify\locales\ro.pak" 
del /f/s/q "%appdata%\Spotify\locales\ru.mo" 
del /f/s/q "%appdata%\Spotify\locales\ru.pak" 
del /f/s/q "%appdata%\Spotify\locales\sk.pak" 
del /f/s/q "%appdata%\Spotify\locales\sl.pak" 
del /f/s/q "%appdata%\Spotify\locales\sr.pak" 
del /f/s/q "%appdata%\Spotify\locales\sv.mo" 
del /f/s/q "%appdata%\Spotify\locales\sv.pak" 
del /f/s/q "%appdata%\Spotify\locales\sw.pak" 
del /f/s/q "%appdata%\Spotify\locales\ta.pak" 
del /f/s/q "%appdata%\Spotify\locales\te.pak" 
del /f/s/q "%appdata%\Spotify\locales\th.mo" 
del /f/s/q "%appdata%\Spotify\locales\th.pak" 
del /f/s/q "%appdata%\Spotify\locales\tr.mo" 
del /f/s/q "%appdata%\Spotify\locales\tr.pak" 
del /f/s/q "%appdata%\Spotify\locales\uk.pak" 
del /f/s/q "%appdata%\Spotify\locales\vi.mo" 
del /f/s/q "%appdata%\Spotify\locales\vi.pak" 
del /f/s/q "%appdata%\Spotify\locales\zh-CN.pak" 
del /f/s/q "%appdata%\Spotify\locales\zh-Hant.mo" 
del /f/s/q "%appdata%\Spotify\locales\zh-TW.pak" 
rmdir "%localappdata%\Spotify\Update"
mkdir %localappdata%\Spotify\Update
icacls %localappdata%\Spotify\Update /deny "%username%":D
icacls %localappdata%\Spotify\Update /deny "%username%":R
icacls %localappdata%\Spotify\Update /deny "%username%":W
cls
exit